import type { Metadata } from 'next';
import Link from 'next/link';
import { Activity, BellRing, CalendarDays, MessageSquareText, UsersRound } from 'lucide-react';
import { logout } from '@/app/login/actions';
import { manilaDay } from '@/lib/operations/metrics';
import { sourceBreakdown, summarizeApsaras, type ApsarasEnquiryRow } from '@/lib/operations/apsaras-metrics';
import { loadApsarasOperations } from '@/lib/server/apsaras-operations';
import { requirePortalClient } from '@/lib/server/client-portal';
import { updateApsarasEnquiry } from './actions';

export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Apsaras Operations',robots:{index:false,follow:false},alternates:{canonical:'/operations/apsaras'}};
const statusLabel=(value:string)=>value.replaceAll('_',' ');
const stamp=(value:string)=>new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const field='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 focus:outline-2 focus:outline-teal-700';
const notices:Record<string,string>={access:'Your account has read-only access.',invalid:'Check the update fields and try again.',save:'The change could not be saved. Check the connection and try again.',saved:'Changes saved.',conflict:'This record changed since you opened it. Review the latest version and try again.'};

function EnquiryCard({row,role}:{row:ApsarasEnquiryRow;role:string}) {
  const urgent=row.priority==='IMMEDIATE'||row.priority==='HIGH';
  const terminal=['confirmed','resolved','closed','lost'].includes(row.status);
  return <details className={`rounded-2xl border bg-white p-4 ${urgent&&!terminal?'border-rose-200':'border-slate-200'}`}>
    <summary className="cursor-pointer list-none"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><strong>{row.guest_name||`${row.record_type==='lead'?'Booking enquiry':'Guest handoff'}`}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] uppercase tracking-wide text-slate-600">{row.record_type}</span>{row.priority&&<span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${urgent?'bg-rose-50 text-rose-800':'bg-amber-50 text-amber-800'}`}>{row.priority}</span>}</div><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-medium text-teal-900">{statusLabel(row.status)}</span></div>
    <p className="mt-2 text-sm text-slate-600">{row.category} · {row.assigned_owner||row.requested_owner||'Unassigned'}</p><p className="mt-2 text-xs text-slate-500">{stamp(row.original_created_at)} · {row.source} · {row.reference_id}</p></summary>
    <div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 text-sm sm:grid-cols-2"><p><span className="text-slate-500">Contact</span><br/>{row.contact||'Not provided'}</p><p><span className="text-slate-500">Stay</span><br/>{row.check_in||'Date pending'} — {row.check_out||'Date pending'}</p><p><span className="text-slate-500">Guests / rooms</span><br/>{row.guests||'Not provided'} · {row.rooms||'Rooms pending'}</p><p><span className="text-slate-500">Room preference</span><br/>{row.room_type||'Not provided'}</p>{(row.special_request||row.last_message||row.reason)&&<p className="sm:col-span-2"><span className="text-slate-500">Request context</span><br/>{row.special_request||row.last_message||row.reason}</p>}</div>
    {role!=='viewer'&&<form action={updateApsarasEnquiry} className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2"><input type="hidden" name="id" value={row.id}/><input type="hidden" name="version" value={row.updated_at}/><label className="text-sm">Assigned owner<input name="owner" defaultValue={row.assigned_owner||row.requested_owner||''} maxLength={120} className={field}/></label><label className="text-sm">Internal note<textarea name="note" defaultValue={row.staff_note||''} maxLength={1000} className={field}/></label><div className="flex flex-wrap gap-2 sm:col-span-2"><button name="action" value="save" className="rounded-xl border border-slate-200 px-3 py-2 text-sm">Save details</button>{row.status==='new'&&<button name="action" value="review" className="rounded-xl bg-slate-100 px-3 py-2 text-sm">Start review</button>}{['new','in_review'].includes(row.status)&&<button name="action" value="contact" className="rounded-xl bg-teal-100 px-3 py-2 text-sm text-teal-900">Guest contacted</button>}{row.record_type==='lead'&&['in_review','contacted'].includes(row.status)&&<button name="action" value="quote" className="rounded-xl bg-blue-50 px-3 py-2 text-sm text-blue-900">Quote sent</button>}{row.record_type==='lead'&&['in_review','contacted','quoted'].includes(row.status)&&<button name="action" value="confirm" className="rounded-xl bg-teal-700 px-3 py-2 text-sm text-white">Booking confirmed</button>}{row.record_type==='handoff'&&['new','in_review','contacted'].includes(row.status)&&<button name="action" value="resolve" className="rounded-xl bg-teal-700 px-3 py-2 text-sm text-white">Resolve handoff</button>}{row.record_type==='lead'&&!terminal&&<button name="action" value="lost" className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-800">Lost / not proceeding</button>}{!['closed','lost'].includes(row.status)&&<button name="action" value="close" className="rounded-xl border border-slate-300 px-3 py-2 text-sm">Close record</button>}</div><p className="text-xs text-slate-500 sm:col-span-2">These actions update the internal workflow only. Contact the guest separately; no message is sent automatically.</p></form>}
  </details>;
}

export default async function ApsarasOperations({searchParams}:{searchParams:Promise<{days?:string;notice?:string}>}) {
  const params=await searchParams;
  const {user,client}=await requirePortalClient('apsaras-tribe');
  const days=params.days==='30'?30:7;
  const today=manilaDay(new Date().toISOString()),dayStart=new Date(`${today}T00:00:00+08:00`).getTime(),end=dayStart+86400000,start=end-days*86400000;
  let data:Awaited<ReturnType<typeof loadApsarasOperations>>|null=null,previous:Awaited<ReturnType<typeof loadApsarasOperations>>|null=null;
  try {[data,previous]=await Promise.all([loadApsarasOperations(new Date(start).toISOString(),new Date(end).toISOString()),loadApsarasOperations(new Date(start-days*86400000).toISOString(),new Date(start).toISOString())]);} catch { /* Fail closed: never substitute invented hotel metrics. */ }
  const current=data?summarizeApsaras(data.periodRows):null,baseline=previous?summarizeApsaras(previous.periodRows):null;
  const sources=data?sourceBreakdown(data.periodRows):[],peakSource=Math.max(1,...sources.map(item=>item.count));
  const dateKeys=Array.from({length:days},(_,index)=>manilaDay(new Date(start+index*86400000).toISOString()));
  const daily=dateKeys.map(day=>({day,count:data?.periodRows.filter(row=>manilaDay(row.original_created_at)===day).length||0})),peak=Math.max(1,...daily.map(item=>item.count));
  const completed=data?.periodRows.filter(row=>['confirmed','resolved','closed','lost'].includes(row.status)).sort((a,b)=>b.original_created_at.localeCompare(a.original_created_at))||[];
  const cards=[
    {title:'Guest enquiries',value:current?.total,old:baseline?.total,icon:MessageSquareText,note:'Qualified enquiries and staff handoffs'},
    {title:'Booking leads',value:current?.leads,old:baseline?.leads,icon:CalendarDays,note:'Requests captured by the AI concierge'},
    {title:'Open follow-ups',value:data?.workQueue.length,icon:UsersRound,note:'All currently actionable records'},
    {title:'High-priority handoffs',value:current?.urgent,old:baseline?.urgent,icon:BellRing,note:'HIGH and IMMEDIATE during this period'},
  ];
  return <main className="min-h-screen bg-[#f4f7f7] text-slate-900"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-8 lg:py-10">
    <header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="rounded-2xl bg-teal-800 p-3 text-white"><Activity/></div><div><p className="text-xs font-semibold tracking-widest text-teal-700">SMEAIHUB OPERATIONS</p><p className="font-semibold">{client.name}</p></div></div><div className="flex items-center gap-3"><Link href="/clients" className="text-sm text-teal-800 underline">All workspaces</Link><form action={logout}><button className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm">Sign out</button></form></div></header>
    <section className="my-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-sm text-slate-500">Hotel guest enquiries / Overview</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Every guest request, clearly owned.</h1><p className="mt-3 text-sm text-slate-500">{manilaDay(new Date(start).toISOString())} — {today} · Asia/Manila · Updated {stamp(new Date().toISOString())}</p></div><div className="flex gap-2">{[7,30].map(value=><Link key={value} href={`?days=${value}`} className={`rounded-xl px-4 py-2 text-sm ${days===value?'bg-teal-800 text-white':'border border-slate-200 bg-white'}`}>{value} days</Link>)}<Link href={`?days=${days}`} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm">Refresh</Link></div></section>
    {params.notice&&<p role="status" className="mb-5 rounded-xl border border-slate-200 bg-white p-4 text-sm">{notices[params.notice]||'The request could not be completed.'}</p>}
    {!data&&<p role="alert" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900">Apsaras operational data is unavailable. Check the data integration and database migration. No metrics have been substituted.</p>}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(({title,value,old,icon:Icon,note})=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-2"><p className="text-sm text-slate-500">{title}</p><Icon size={20} className="text-teal-700"/></div><p className="my-4 text-3xl font-semibold tracking-tight">{value??'—'}</p><p className="text-xs text-slate-500">{note}</p>{typeof value==='number'&&typeof old==='number'&&<p className="mt-3 text-xs text-slate-600">{value-old>=0?'+':''}{value-old} vs previous {days} days</p>}</article>)}</section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[2fr_1fr]"><article className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Daily enquiry activity</h2><p className="mt-1 text-sm text-slate-500">New leads and staff handoffs recorded by the concierge.</p><div className="mt-6 flex h-48 items-end gap-1">{daily.map(item=><div className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2" key={item.day}><span className="text-[10px] text-slate-500 opacity-0 group-hover:opacity-100">{item.count}</span><div className="w-full rounded-t bg-teal-600" style={{height:`${Math.max(3,item.count/peak*145)}px`}}/><span className="hidden text-[9px] text-slate-400 sm:block">{item.day.slice(5)}</span></div>)}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Enquiry sources</h2><p className="mt-1 text-sm text-slate-500">Where captured demand is entering.</p><div className="mt-5 space-y-4">{sources.map(item=><div key={item.source}><div className="flex justify-between text-sm"><span className="capitalize">{item.source}</span><strong>{item.count}</strong></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-amber-500" style={{width:`${item.count/peakSource*100}%`}}/></div></div>)}{data&&!sources.length&&<p className="text-sm text-slate-500">No enquiry sources in this period.</p>}</div></article></section>
    <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Guest follow-up queue</h2><p className="mt-2 text-sm text-slate-500">Assign, contact and record outcomes. Urgent handoffs stay visible until resolved.</p></div><span className="rounded-full bg-white px-3 py-2 text-sm text-slate-600">{data?.workQueue.length??'—'} open</span></div><div className="mt-4 space-y-3">{data?.workQueue.map(row=><EnquiryCard key={row.id} row={row} role={client.role}/>)}{data&&!data.workQueue.length&&<p className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">No open guest follow-ups.</p>}</div></section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Completed outcomes</h2><p className="mt-2 text-sm text-slate-500">Confirmed, resolved, closed and lost records created in the selected period.</p><div className="mt-4 space-y-3">{completed.map(row=><EnquiryCard key={row.id} row={row} role={client.role}/>)}{data&&!completed.length&&<p className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">No completed outcomes in this period.</p>}</div></section>
    <footer className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-500"><strong className="text-slate-700">Data coverage</strong><p className="mt-2">Source: Apsaras AI Concierge booking enquiries and human handoffs. The dashboard reports captured demand and staff workflow only. PMS room availability, OTA reservations, payments, occupancy and hotel revenue are not connected and are never estimated.</p><p className="mt-2">Signed in as {user.email}. Account permissions are verified on the server and in the database; workflow changes are attributed to this account.</p></footer>
  </div></main>;
}
