import type { Metadata } from 'next';
import Link from 'next/link';
import { Activity, ArrowUpRight, CalendarCheck, CircleDollarSign, ClipboardList, MessageCircle, ShieldCheck } from 'lucide-react';
import { hasOperationsSession, loadOperations } from '@/lib/server/kazuko-operations';
import { dailyVolume, manilaDay, summarize, type RequestRow } from '@/lib/operations/metrics';
import { resolveException, signIn, signOut, syncWebsiteRequests, updateRequest } from './actions';
export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Kazuko Operations', robots: { index: false, follow: false }, alternates: { canonical: '/operations/kazuko' } };
const money = (value: number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP', maximumFractionDigits: 2 }).format(value);
const stamp = (value: string) => new Intl.DateTimeFormat('en-PH', { timeZone: 'Asia/Manila', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
const notices: Record<string,string> = { access: 'Access key not accepted.', invalid: 'Check the required fields and amount.', save: 'Could not save. Check the connection and try again.', saved: 'Changes saved.', conflict: 'This record changed since you opened it. Review the latest version before saving again.', website_synced: 'Website reservations are up to date.', website_pending: 'Some website reservations are still waiting to sync. Retry after 30 seconds; contact support if this continues.', website_unavailable: 'Website reservation sync is unavailable. Saved requests remain on the booking website. Contact support to check the connection.' };
const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 focus:outline-2 focus:outline-emerald-600';
const statusLabel = (value: string) => value.replaceAll('_', ' ');
function RequestCard({ row }: { row: RequestRow }) {
  const requestedTime = row.requested_datetime_text || `${row.requested_date || 'Date pending'} · ${row.requested_time || 'Time pending'}`;
  return <details className="rounded-2xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{row.guest_name || (row.request_type === 'reservation' ? 'Reservation request' : 'Customer handoff')}</strong><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-medium text-amber-900">{statusLabel(row.status)}</span></div><p className="mt-2 text-sm text-slate-500">{row.request_type === 'reservation' ? `${requestedTime} · ${row.party_size || '?'} guests` : statusLabel(row.handoff_reason)} · {row.owner_name || 'Unassigned'}</p><p className="mt-2 text-xs text-slate-500">{row.intake_source === 'web' ? 'Website' : 'WhatsApp'}{row.external_request_id ? ` · Reference ${row.external_request_id}` : ''}{row.intake_source === 'web' ? ` · Received ${stamp(row.created_at)}` : ''}</p></summary>
  <form action={updateRequest} className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2">
    <input type="hidden" name="id" value={row.id}/><input type="hidden" name="version" value={row.updated_at}/>
    <p className="text-sm sm:col-span-2">Contact: {row.contact_number || 'Not provided'} · Special request: {row.special_request || 'Not provided'}</p>
    <label className="text-sm">Your name (required)<input name="actor" required maxLength={80} className={inputClass} autoComplete="name"/></label>
    <label className="text-sm">Assigned owner<input name="owner" defaultValue={row.owner_name || ''} maxLength={80} className={inputClass}/></label>
    <label className="text-sm sm:col-span-2">Staff note<textarea name="note" defaultValue={row.staff_note || ''} maxLength={1000} className={inputClass}/></label>
    {['confirmed','arrived'].includes(row.status) && <label className="text-sm sm:col-span-2">Recorded bill (PHP, optional)<input type="number" name="amount" min="0" max="9999999.99" step="0.01" defaultValue={row.sale_amount_php ?? ''} className={inputClass}/><span className="text-xs text-slate-500">Record on arrival. Blank preserves an existing amount; zero means a recorded zero bill.</span></label>}
    <div className="flex flex-wrap gap-2 sm:col-span-2">
      <button name="action" value="save" className="rounded-xl border border-slate-200 px-3 py-2 text-sm">Save details</button>
      {row.status === 'pending_staff_confirmation' && <button name="action" value="review" className="rounded-xl bg-slate-100 px-3 py-2 text-sm">Start review</button>}
      {row.request_type === 'reservation' && ['pending_staff_confirmation','in_review'].includes(row.status) && <button name="action" value="confirm" className="rounded-xl bg-emerald-700 px-3 py-2 text-sm text-white">Confirm reservation</button>}
      {row.request_type === 'reservation' && row.status === 'confirmed' && <button name="action" value="arrive" className="rounded-xl bg-emerald-700 px-3 py-2 text-sm text-white">Record arrival</button>}
      {row.request_type === 'reservation' && ['pending_staff_confirmation','in_review','confirmed'].includes(row.status) && <button name="action" value="cancel" className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-800">Cancel request</button>}
      {row.request_type === 'handoff' && ['pending_staff_confirmation','in_review'].includes(row.status) && <button name="action" value="resolve" className="rounded-xl bg-emerald-700 px-3 py-2 text-sm text-white">Mark resolved</button>}
    </div><p className="text-xs text-slate-500 sm:col-span-2">Updates are internal records. Notify the guest separately; this action does not send a WhatsApp message.</p>
  </form></details>;
}
export default async function KazukoOperations({ searchParams }: { searchParams: Promise<{ days?: string; notice?: string }> }) {
  const params = await searchParams;
  const notice = params.notice ? notices[params.notice] : undefined;
  const authorized = await hasOperationsSession();
  if (!authorized) return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-5 text-slate-900"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-sm"><ShieldCheck className="mb-5 text-emerald-700" size={36}/><p className="text-xs font-semibold tracking-widest text-emerald-700">SMEAIHUB / KAZUKO</p><h1 className="mt-3 text-3xl font-semibold">Your operations, in focus.</h1><p className="mt-3 text-sm text-slate-500">Private access for the Kazuko operations team.</p>{notice && <p role="alert" className="mt-4 text-sm text-rose-700">{notice}</p>}<form action={signIn} className="mt-6 space-y-4"><label className="block text-sm">Operations access key<input name="token" type="password" required maxLength={256} autoComplete="current-password" className={inputClass}/></label><button className="w-full rounded-xl bg-emerald-700 py-3 font-medium text-white">Open dashboard</button></form><p className="mt-5 text-xs text-slate-500">Access is disabled until a private operations key is configured.</p></section></main>;
  const days = params.days === '30' ? 30 : 7;
  const today = manilaDay(new Date().toISOString());
  const dayStart = new Date(`${today}T00:00:00+08:00`).getTime();
  const end = dayStart + 86400000;
  const start = end - days * 86400000;
  let data: Awaited<ReturnType<typeof loadOperations>> | null = null;
  let previous: Awaited<ReturnType<typeof loadOperations>> | null = null;
  try { [data, previous] = await Promise.all([loadOperations(new Date(start).toISOString(), new Date(end).toISOString()), loadOperations(new Date(start - days * 86400000).toISOString(), new Date(start).toISOString())]); } catch { /* Fail closed: no invented zero values on a connection error. */ }
  const current = data ? summarize(data.messages, data.requests) : null;
  const baseline = previous ? summarize(previous.messages, previous.requests) : null;
  const trend = data ? dailyVolume(data.messages, Array.from({ length: days }, (_, i) => manilaDay(new Date(start + i * 86400000).toISOString()))) : [];
  const peak = Math.max(1, ...trend.map(t => t.count));
  const cards = [
    { title: 'WhatsApp inbound messages', value: current?.messages, old: baseline?.messages, icon: MessageCircle, note: 'WhatsApp records only; website bookings excluded' },
    { title: 'Reservation requests', value: current?.reservations, old: baseline?.reservations, icon: CalendarCheck, note: 'Website and WhatsApp requests; staff confirms availability' },
    { title: 'Recorded arrivals', value: current?.arrived, old: baseline?.arrived, icon: ClipboardList, note: 'From requests created in this period' },
    { title: 'Reservation-linked sales', value: current?.revenue == null ? undefined : money(current.revenue), icon: CircleDollarSign, note: current ? `${current.recordedSales} recorded bills · not AI-attributed growth` : 'Bill data unavailable' },
  ];
  const history = data?.requests.filter(r => !['pending_staff_confirmation','in_review','confirmed'].includes(r.status)).sort((a,b)=>b.created_at.localeCompare(a.created_at)) || [];
  return <main className="min-h-screen bg-[#f5f7f9] text-slate-900"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-8 lg:py-10">
    <header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-800 p-3 text-white"><Activity/></div><div><p className="text-xs font-semibold tracking-widest text-emerald-700">SMEAIHUB OPERATIONS</p><p className="font-semibold">Kazuko Ramenba</p></div></div><form action={signOut}><button className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm">Sign out</button></form></header>
    <section className="my-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-sm text-slate-500">Restaurant operations / Overview</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">A clearer view of your business.</h1><p className="mt-3 text-sm text-slate-500">{manilaDay(new Date(start).toISOString())} — {today} · Asia/Manila · Updated {stamp(new Date().toISOString())}</p></div><div className="flex flex-wrap gap-2">{[7,30].map(d=><Link key={d} href={`?days=${d}`} className={`rounded-xl px-4 py-2 text-sm ${days === d ? 'bg-emerald-800 text-white' : 'border border-slate-200 bg-white'}`}>{d} days</Link>)}<Link href={`?days=${days}`} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm">Refresh</Link><form action={syncWebsiteRequests}><button className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm text-emerald-900">Sync website bookings</button></form></div></section>
    {notice && <p role="status" className="mb-5 rounded-xl border border-slate-200 bg-white p-4 text-sm">{notice}</p>}
    {!data && <p role="alert" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900">Operational data is unavailable. Check the database connection and apply the operations migration. No metrics have been substituted.</p>}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(({title,value,old,icon: Icon,note})=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-2"><p className="text-sm text-slate-500">{title}</p><Icon size={20} className="text-emerald-700"/></div><p className="my-4 text-3xl font-semibold tracking-tight">{value ?? '—'}</p><p className="text-xs text-slate-500">{note}</p>{typeof value === 'number' && old !== undefined && <p className="mt-3 text-xs text-slate-600">{value - old >= 0 ? '+' : ''}{value-old} vs previous {days} days{old > 0 ? ` (${((value-old)/old*100).toFixed(1)}%)` : ' · percentage unavailable'}</p>}</article>)}</section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[2fr_1fr]"><article className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Daily inbound activity</h2><p className="mt-1 text-sm text-slate-500">Message volume; not unique enquiries or sales. The current period includes today and is not yet complete.</p>{data ? <div className="mt-6 flex h-40 items-end gap-1 sm:gap-2" aria-label="Daily message counts">{trend.map(t=><div key={t.day} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] text-slate-500">{t.count}</span><div title={`${t.day}: ${t.count} messages`} className="w-full rounded-t-md bg-emerald-600" style={{height: `${Math.max(2,t.count/peak*100)}px`}}/><span className="text-[9px] text-slate-500">{t.day.slice(8)}</span></div>)}</div> : <p className="py-10 text-sm text-slate-500">Waiting for operational data.</p>}</article><article className="rounded-2xl bg-emerald-900 p-6 text-white"><h2 className="text-lg font-semibold">Needs attention</h2><p className="mt-5 text-4xl font-semibold">{data ? data.workQueue.length : '—'}</p><p className="mt-1 text-sm text-emerald-100">Open requests across all dates</p><p className="mt-5 text-sm text-emerald-100">{data ? data.exceptions.length : '—'} message exceptions to investigate</p><a href="#work-queue" className="mt-5 inline-flex items-center gap-2 text-sm font-medium">Open work queue <ArrowUpRight size={16}/></a></article></section>
    <section id="work-queue" className="mt-8"><h2 className="text-xl font-semibold">Guest requests & staff follow-up</h2><p className="mt-2 text-sm text-slate-500">Review, assign and record outcomes. Open requests are shown regardless of the reporting period.</p><div className="mt-4 space-y-3">{data?.workQueue.map(row=><RequestCard key={row.id} row={row}/>)}{data && !data.workQueue.length && <p className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">No open requests.</p>}</div></section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Message exceptions</h2><p className="mt-2 text-sm text-slate-500">Investigate delivery before closing. Closing records a manual resolution and never resends a reply.</p><div className="mt-4 space-y-3">{data?.exceptions.map(row=><details key={row.id} className="rounded-2xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm">{stamp(row.created_at)} · {statusLabel(row.processing_status)} · {row.error_code || 'Processing has not completed'}</summary>{row.processing_status === 'processing' ? <p className="mt-3 text-sm text-amber-800">Processing records require technical investigation and cannot be closed here.</p> : <form action={resolveException} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={row.id}/><input type="hidden" name="version" value={row.updated_at}/><label className="text-sm">Your name<input name="actor" required maxLength={80} className={inputClass}/></label><label className="text-sm">Resolution note<input name="note" required maxLength={1000} className={inputClass}/></label><button className="rounded-xl bg-slate-800 px-4 py-2 text-sm text-white sm:col-span-2">Record manual resolution</button></form>}</details>)}{data && !data.exceptions.length && <p className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">No unresolved message exceptions.</p>}</div></section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Outcomes & recorded bills</h2><p className="mt-2 text-sm text-slate-500">Requests created within the selected period. Expand an arrival to add or correct its bill.</p><div className="mt-4 space-y-3">{history.map(row=><RequestCard key={row.id} row={row}/>)}{data && !history.length && <p className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">No completed outcomes in this period.</p>}</div></section>
    <footer className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-500"><strong className="text-slate-700">Data coverage</strong><p className="mt-2">Source: website reservation requests, WhatsApp processing records and staff-entered outcomes. Website requests retain their original creation date and requested date/time wording; staff must clarify ambiguous dates with the guest. Sales totals include only recorded bills from these reservations, not total restaurant revenue. Marketing, reviews, POS and labour costs are not connected. No savings or AI revenue uplift is claimed.</p><p className="mt-2">Initial access uses one Kazuko-specific team key. Operator names are self-reported; individual accounts and role-based permissions are not yet available.</p></footer>
  </div></main>;
}
