import Link from 'next/link';
import { portalClients, portalFetch, requirePortalAdmin } from '@/lib/server/client-portal';
import { legacyKazukoEnabled } from '@/lib/server/legacy-kazuko-access';
import { manageMember, disableLegacy } from './actions';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Client Members', robots: { index: false, follow: false } };
export default async function Members({ searchParams }: { searchParams: Promise<{notice?: string}> }) {
  const user = await requirePortalAdmin();
  const [clients, members] = await Promise.all([portalClients(), portalFetch<{tenant_slug:string;email:string;role:string;active:boolean}[]>('rest/v1/rpc/portal_member_list', user.token, {})]);
  const legacy = await legacyKazukoEnabled();
  const {notice} = await searchParams;
  const field = 'mt-2 w-full rounded-xl border border-slate-200 bg-white p-3';
  return <main className="min-h-screen bg-slate-50 px-5 py-10 text-slate-900"><div className="mx-auto max-w-5xl"><Link href="/clients" className="text-emerald-800 underline">All workspaces</Link><h1 className="mt-8 text-3xl font-semibold">Client members</h1><p className="mt-3 text-sm text-slate-600">Assign access to an existing, confirmed employee account. Managers can record bills; staff can process requests; viewers have read-only access.</p>{notice && <p role="status" className="mt-5 rounded-xl bg-white p-4">{notice === 'saved' ? 'Membership saved.' : notice === 'legacy_disabled' ? 'Shared-key access disabled. Existing team-key sessions have been revoked.' : 'Could not save. Check the email, confirmed Auth account, role and database connection.'}</p>}<form action={manageMember} className="mt-8 grid gap-4 rounded-2xl border bg-white p-6 sm:grid-cols-2"><label>Client<select name="tenant" className={field}>{clients.map(c=><option value={c.tenant_slug} key={c.tenant_slug}>{c.name}</option>)}</select></label><label>Employee email<input name="email" type="email" maxLength={254} required className={field}/></label><label>Role<select name="role" className={field}><option value="staff">Staff</option><option value="manager">Manager</option><option value="viewer">Viewer</option></select></label><label>Access<select name="active" className={field}><option value="true">Enabled</option><option value="false">Disabled</option></select></label><button className="rounded-xl bg-emerald-800 px-4 py-3 text-white sm:col-span-2">Save membership</button></form><div className="mt-8 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead><tr><th className="p-4">Client</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">Access</th></tr></thead><tbody>{members.map(m=><tr key={`${m.tenant_slug}:${m.email}`} className="border-t"><td className="p-4">{clients.find(c=>c.tenant_slug===m.tenant_slug)?.name || m.tenant_slug}</td><td className="p-4">{m.email}</td><td className="p-4">{m.role}</td><td className="p-4">{m.active ? 'Enabled' : 'Disabled'}</td></tr>)}</tbody></table>{!members.length && <p className="p-4 text-slate-500">No employee memberships assigned yet.</p>}</div>{legacy && <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-semibold">Complete the Kazuko account migration</h2><p className="mt-3 text-sm">After the Kazuko team has verified employee account access, disable shared-key login. This also revokes existing shared-key sessions. Account login remains available.</p><form action={disableLegacy} className="mt-4"><button className="rounded-xl bg-slate-900 px-4 py-3 text-white">Disable Kazuko shared-key access</button></form></section>}</div></main>;
}
